options:
  CU_DB:
    type: string
    description: "MongoDB connection string"
  NODE_ENV:
    default: staging
    type: string
    description: "Node environment"
  COBALT_PORT:
    type: string
    description: "Port/socket that Cobalt will run on"
  CO_AVOID_BOX_CHECK:
    type: string
    description: "If set, avoids box check so local development works"
  NODETIME_KEY:
    type: string
    description: "Nodetime.com API key (profiling tool)"
  CO_NODETIME_APP:
    type: string
    description: "Name of the Nodetime app"
  ALLOWED_IP:
    type: string
    description: "List of allowed IPs, one per line"
  SSL_CRT:
    description: "SSL certificate"
    type: string
  SSL_KEY:
    description: "SSL private key"
    type: string
  EBS_VOLUME:
    description: "EBS volume to attach to (not currently used)"
    type: string
  INSTALL_ALL_PACKAGES:
    default: "no"
    description: "Install all the basejail packages for a live cobalt instance"
    type: string
  CO_STORAGE_DIR:
    default: "/ebs"
    description: "Where to store all cobalt data"
    type: string
  MUNIN_SERVER:
    description: "IP of munin server to allow"
    type: string
